name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  docker:
    environment: Docker Build
    runs-on: ubuntu-22.04
    steps:
      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/htmx-russh-games
            ${{ vars.REGISTRY_HOSTNAME }}/${{ vars.REGISTRY_USERNAME }}/htmx-russh-games
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN  }}
      - name: Login to Forgejo Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOSTNAME }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PUSH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: |
            linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
